export const allProjectsData = [
    {
      slug: "ecommerce-platform",
      title: "E-commerce Platform",
      description: "A full-featured e-commerce site built with Next.js, Stripe for payments, and a custom CMS for product management.",
      longDescription: "A full-featured e-commerce site built with Next.js, Stripe for payments, and a custom CMS for product management. This project involved creating a seamless shopping experience, from product discovery to checkout. The backend is powered by Node.js and manages inventory, orders, and customer data securely.",
      image: "https://placehold.co/1200x600.png",
      imageHint: "online store checkout",
      link: "/projects/ecommerce-platform",
      githubLink: "#",
      tags: ["Next.js", "React", "Stripe", "Tailwind CSS", "Node.js"],
      category: "Web",
    },
    {
      slug: "data-visualization-dashboard",
      title: "Data Visualization Dashboard",
      description: "An interactive dashboard for visualizing complex datasets using D3.js and React, enabling real-time data exploration.",
      longDescription: "An interactive dashboard for visualizing complex datasets using D3.js and React, enabling real-time data exploration. It allows users to filter, sort, and drill down into data with various chart types. The architecture is designed for performance, handling large volumes of data efficiently.",
      image: "https://placehold.co/1200x600.png",
      imageHint: "data dashboard charts",
      link: "/projects/data-visualization-dashboard",
      githubLink: "#",
      tags: ["React", "D3.js", "Node.js", "Express"],
      category: "Web",
    },
    {
      slug: "ai-content-generator",
      title: "AI-Powered Content Generator",
      description: "A web app that leverages generative AI to create marketing copy and blog posts, built with Python, Flask, and a React frontend.",
      longDescription: "A web app that leverages generative AI to create marketing copy and blog posts, built with Python, Flask, and a React frontend. Users can specify a topic and tone, and the AI generates high-quality content. The project required fine-tuning a large language model for specific content styles.",
      image: "https://placehold.co/1200x600.png",
      imageHint: "artificial intelligence writing",
      link: "/projects/ai-content-generator",
      githubLink: "#",
      tags: ["Python", "Flask", "React", "AI", "NLP"],
      category: "AI",
    },
    {
      slug: "mobile-fitness-app",
      title: "Mobile Fitness App",
      description: "A cross-platform mobile app for tracking workouts and nutrition, built with React Native and Firebase.",
      longDescription: "A cross-platform mobile app for tracking workouts and nutrition, built with React Native and Firebase. Features include personalized workout plans, progress tracking, and social sharing. Firebase is used for real-time database updates and user authentication.",
      image: "https://placehold.co/1200x600.png",
      imageHint: "mobile fitness tracker",
      link: "/projects/mobile-fitness-app",
      githubLink: "#",
      tags: ["React Native", "Firebase", "iOS", "Android"],
      category: "Mobile",
    },
    {
      slug: "project-management-tool",
      title: "Project Management Tool",
      description: "A collaborative tool for teams to manage tasks, projects, and deadlines, featuring a real-time Kanban board.",
      longDescription: "A collaborative tool for teams to manage tasks, projects, and deadlines, featuring a real-time Kanban board. Built with the MERN stack (MongoDB, Express, React, Node.js) and Socket.io for live updates. It helps teams stay organized and improves productivity.",
      image: "https://placehold.co/1200x600.png",
      imageHint: "kanban board software",
      link: "/projects/project-management-tool",
      githubLink: "#",
      tags: ["React", "Node.js", "Socket.io", "MongoDB"],
      category: "Web",
    },
    {
      slug: "iot-smart-home-system",
      title: "IoT Smart Home System",
      description: "A system to control smart home devices from a central dashboard, using Raspberry Pi, Node.js, and MQTT.",
      longDescription: "A system to control smart home devices from a central dashboard, using Raspberry Pi, Node.js, and MQTT. This project allows users to automate lighting, temperature, and security. The dashboard provides a user-friendly interface to manage all connected devices.",
      image: "https://placehold.co/1200x600.png",
      imageHint: "smart home dashboard",
      link: "/projects/iot-smart-home-system",
      githubLink: "#",
      tags: ["IoT", "Raspberry Pi", "Node.js", "MQTT"],
      category: "IoT",
    },
    {
      slug: "recipe-sharing-app",
      title: "Recipe Sharing App",
      description: "A social platform for users to share and discover new recipes, with features like meal planning and shopping lists.",
      longDescription: "A social platform for users to share and discover new recipes, with features like meal planning and shopping lists. Built with Vue.js and Firebase, it offers a seamless and engaging user experience for food enthusiasts.",
      image: "https://placehold.co/1200x600.png",
      imageHint: "food recipe website",
      link: "/projects/recipe-sharing-app",
      githubLink: "#",
      tags: ["Vue.js", "Firebase", "Vuetify"],
      category: "Web",
    },
    {
      slug: "ar-navigation-app",
      title: "AR Navigation App",
      description: "An augmented reality mobile app that overlays navigation directions onto the real world view from the phone's camera.",
      longDescription: "An augmented reality mobile app that overlays navigation directions onto the real world view from the phone's camera. Using ARKit for iOS, it provides an intuitive and futuristic way to navigate urban environments.",
      image: "https://placehold.co/1200x600.png",
      imageHint: "augmented reality navigation",
      link: "/projects/ar-navigation-app",
      githubLink: "#",
      tags: ["ARKit", "Swift", "CoreLocation"],
      category: "Mobile",
    },
  ];
  
  export type Project = (typeof allProjectsData)[0];
  